---
abstract: "A POE component that provides non-blocking access to Win32::Service.\r"
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-Win32-Service
no_index:
  directory:
    - mylib
    - inc
    - t
requires:
  Carp: 0
  POE: 0.38
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Wheel::Run: 0
  Win32: 0
  Win32::Service: 0
  perl: 5.000
  strict: 0
  vars: 0
tests: 't/*.t xt/*.t'
version: 1.22
