# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Win32-Service
version:      0.50
version_from: lib/POE/Component/Win32/Service.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.31
    Win32::Service:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
