---
abstract: "A POE component that provides non-blocking access to Win32::Service.\r"
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.86'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Win32-Service
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  POE: 1.005
  POE::Filter::Line: 0
  POE::Filter::Reference: 0
  POE::Wheel::Run: 0
  Win32: 0
  Win32::Service: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-win32-service/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-win32-service.git
version: 1.24
