author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Component::Win32::Service
name: POE-Component-Win32-Service
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  POE: 0.31
  Win32::Service: 0
version: 1.04
